ingress:
  hosts:
    - host: staging.chart-example.local
      paths:
        - path: /onboarding
          pathType: Prefix
          backend:
            service:
              name: onboarding
              port:
                number: 80
        - path: /onboarding-alt
          pathType: Prefix
          backend:
            service:
              name: onboarding
              port:
                number: 8001