ingress:
  hosts:
    - host: dev.chart-example.local
      paths:
        - path: /admin
          pathType: Prefix
          backend:
            service:
              name: admin
              port:
                number: 80
        - path: /admin-alt
          pathType: Prefix
          backend:
            service:
              name: admin
              port:
                number: 8001