apiVersion: v1
kind: Service
metadata:
  name: {{ include "payment.fullname" . }}
  {{ .Chart.Name }}-{{ .Chart.Version | replace "." "-" }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "payment.labels" . | nindent 4 }}
    {{- include "payment.argocdLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "payment.selectorLabels" . | nindent 4 }}
