apiVersion: v1
kind: Secret
metadata:
  name: {{ include "onboarding.fullname" . }}-secret
  labels:
    {{- include "onboarding.labels" . | nindent 4 }}
type: Opaque
# data:
# {{ (.Files.Get ".env" | b64enc) | indent 2 }}
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
