ingress:
  hosts:
    - host: dev.chart-example.local
      paths:
        - path: /payment
          pathType: Prefix
          backend:
            service:
              name: payment
              port:
                number: 80
        - path: /payment-alt
          pathType: Prefix
          backend:
            service:
              name: payment
              port:
                number: 8001